import { Translation } from "primeng/api";

export const Translate:Translation = {
    "startsWith": "Começa com",
    "contains": "Contém",
    "notContains": "Não contém",
    "endsWith": "Ends com",
    "equals": "Igual",
    "notEquals": "Não igual",
    "noFilter": "Sem Filtro",
    "lt": "Menor que",
    "lte": "Menor que ou igual a",
    "gt": "Maior que",
    "gte": "Maior que ou igual a",
    "is": "É",
    "isNot": "Não é",
    "before": "Antes",
    "after": "Depois",
    "dateIs": "Data é",
    "dateIsNot": "Data não é",
    "dateBefore": "Data é antes",
    "dateAfter": "Data é depois",
    "clear": "Limpar",
    "apply": "Aplicar",
    "matchAll": "Corresponder todos",
    "matchAny": "Corresponder qualquer um",
    "addRule": "Adicionar Regra",
    "removeRule": "Remover Regra",
    "accept": "Sim",
    "reject": "Não",
    "choose": "Escolha",
    "upload": "Upload",
    "cancel": "Cancelar",
    "dayNames": ["Domingo", "Segunda", "Terça", "Quarta", "Quinta", "Sexta", "Sábado"],
    "dayNamesShort": ["Dom", "Seg", "Ter", "Qua", "Qui", "Sex", "Sab"],
    "dayNamesMin": ["D","S","T","Q","Q","S","S"],
    "monthNames": ["Janeiro","Fevereiro","Março","Abril","Maio","Junho","Julho","Agosto","Setembro","Outubro","Novembro","Dezembro"],
    "monthNamesShort": ["Jan", "Fev", "Mar", "Abr", "Mai", "Jun","Jul", "Ago", "Set", "Out", "Nov", "Dez"],
    "dateFormat": "dd/mm/yy",
    "firstDayOfWeek": 0,
    "today": "Hoje",
    "weekHeader": "Sm",
    "weak": "Fraco",
    "medium": "Médio",
    "strong": "Forte",
    "passwordPrompt": "Informe uma senha",
    "emptyMessage": "Nenhum resultado encontrado",
    "emptyFilterMessage": "Nenhum resultado encontrado",
    "pending": "Pendente",
    "chooseYear": "Escolha Ano",
    "chooseMonth": "Escolha Mês",
    "chooseDate": "Escolha Data",
    "prevDecade": "Década Anterior",
    "nextDecade": "Década Seguinte",
    "prevYear": "Ano Anterior",
    "nextYear": "Ano Seguinte",
    "prevMonth": "Mês Anterior",
    "nextMonth": "Mês Seguinte",
    "prevHour": "Hora Anterior",
    "nextHour": "Hora Seguinte",
    "prevMinute": "Minuto Anterior",
    "nextMinute": "Minuto Seguinte",
    "prevSecond": "Segundo Anterior",
    "nextSecond": "Segundo Seguinte",
    "am": "am",
    "pm": "pm",
    "searchMessage": "{0} resultados disponíveis",
    "selectionMessage": "{0} itens selecionados",
    "emptySelectionMessage": "Nenhum item selecionado",
    "emptySearchMessage": "Nenhum resultado encontrado",
    "aria":{
        "trueLabel": "Verdadeiro",
        "falseLabel": "Falso",
        "nullLabel": "Não Selecionado",
        "star": "1 estrela",
        "stars": "{star} estrelas",
        "selectAll": "Selecionar todos os items",
        "unselectAll": "Desselecionar todos os items",
        "close": "Fechar",
        "previous": "Anterior",
        "next": "Seguinte",
        "navigation": "Navegação",
        "scrollTop": "Rolar para o Topo",
        "moveTop": "Mover para o Topo",
        "moveUp": "Mover para Cima",
        "moveDown": "Mover para Baixo",
        "moveBottom": "Mover para o Final",
        "moveToTarget": "Mover para o Alvo",
        "moveToSource": "Mover para a Fonte",
        "moveAllToTarget": "Mover Todos para o Alvo",
        "moveAllToSource": "Mover Todos par a Fonte",
        "pageLabel": "{page}",
        "firstPageLabel": "Primeira Página",
        "lastPageLabel": "Última Página",
        "nextPageLabel": "Página Seguinte",
        "prevPageLabel": "Página Anterior",
        "rowsPerPageLabel": "Linhas por página",
        "jumpToPageDropdownLabel": "Pular para Menu da Página",
        "jumpToPageInputLabel": "Pular para Campo da Página",
        "selectRow": "Linha Selecionada",
        "unselectRow": "Linha Não Selecionada",
        "expandRow": "Linha Expandida",
        "collapseRow": "Linha Recolhida",
        "showFilterMenu": "Mostrar Menu de Filtro",
        "hideFilterMenu": "Esconder Menu de Filtro",
        "filterOperator": "Operador de Filtro",
        "filterConstraint": "Restrição de Filtro",
        "editRow": "Editar Linha",
        "saveEdit": "Salvar Editar",
        "cancelEdit": "Cancelar Editar",
        "listView": "Exibição em Lista",
        "gridView": "Exibição em Grade",
        "slide": "Deslizar",
        "slideNumber": "{slideNumber}",
        "zoomImage": "Ampliar Imagem",
        "zoomIn": "Mais Zoom",
        "zoomOut": "Menos Zoom",
        "rotateRight": "Girar à Direita",
        "rotateLeft": "Girar à Esquerda"
    }
}