import { Translation } from "primeng/api";

export const Translate:Translation = {
    "startsWith": "Começa com",
    "contains": "Contém",
    "notContains": "Não contém",
    "endsWith": "Ends com",
    "equals": "Igual",
    "notEquals": "Não igual",
    "noFilter": "Sem Filtro",
    "lt": "Menor que",
    "lte": "Menor que ou igual a",
    "gt": "Maior que",
    "gte": "Maior que ou igual a",
    "is": "É",
    "isNot": "Não é",
    "before": "Antes",
    "after": "Depois",
    "dateIs": "Data é",
    "dateIsNot": "Data não é",
    "dateBefore": "Data é antes",
    "dateAfter": "Data é depois",
    "clear": "Limpar",
    "apply": "Aplicar",
    "matchAll": "Corresponder todos",
    "matchAny": "Corresponder qualquer um",
    "addRule": "Adicionar Regra",
    "removeRule": "Remover Regra",
    "accept": "Sim",
    "reject": "Não",
    "choose": "Escolha",
    "upload": "Upload",
    "cancel": "Cancelar",
    "dayNames": ["Domingo", "Segunda", "Terça", "Quarta", "Quinta", "Sexta", "Sábado"],
    "dayNamesShort": ["Dom", "Seg", "Ter", "Qua", "Qui", "Sex", "Sab"],
    "dayNamesMin": ["D","S","T","Q","Q","S","S"],
    "monthNames": ["Janeiro","Fevereiro","Março","Abril","Maio","Junho","Julho","Agosto","Setembro","Outubro","Novembro","Dezembro"],
    "monthNamesShort": ["Jan", "Fev", "Mar", "Abr", "Mai", "Jun","Jul", "Ago", "Set", "Out", "Nov", "Dez"],
    "dateFormat": "dd/mm/yy",
    "firstDayOfWeek": 0,
    "today": "Hoje",
    "weekHeader": "Sm",
    "weak": "Fraco",
    "medium": "Médio",
    "strong": "Forte",
    "passwordPrompt": "Informe uma senha",
    "emptyMessage": "Nenhum resultado encontrado",
    "emptyFilterMessage": "Nenhum resultado encontrado"
}