CREATE TABLE ENDERECO(
	ID BIGSERIAL NOT NULL PRIMARY KEY,
	LOGRADOURO VARCHAR(150),
	NUMERO VARCHAR(50),
	BAIRRO VARCHAR(100),
	MUNICIPIO VARCHAR(150),
	CEP VARCHAR(9),
	ESTADO VARCHAR(20),
	PAIS VARCHAR(100)
);