CREATE TABLE RESIDENTE(
	ID BIGSERIAL NOT NULL PRIMARY KEY,
	NOME VARCHAR(150),
	IDADE INTEGER,
	CPF VARCHAR(11),
	TELEFONE VARCHAR(11),
	EMAIL VARCHAR(100),
	SITUACAO VARCHAR(10),
	TIPOESTADIA VARCHAR(6),
	DATAHORAINGRESSO TIMESTAMPTZ,
	DATAHORAPREVISAOSAIDA TIMESTAMPTZ,
	IDENDERECO BIGINT,
	CONSTRAINT FK_ENDERECO_RESIDENTE FOREIGN KEY(IDENDERECO) REFERENCES ENDERECO(ID)
);