CREATE TABLE PROFISSIONAL(
	ID BIGSERIAL NOT NULL PRIMARY KEY,
	FUNCAO VARCHAR(20),
	DATAADMISSAO DATE,
	SALARIO REAL,
	SITUACAO VARCHAR(10),
	NOME VARCHAR(150),
	IDADE INTEGER,
	CPF VARCHAR(11),
	TELEFONE VARCHAR(11),
	EMAIL VARCHAR(100),
	IDENDERECO BIGINT,
	CONSTRAINT FK_ENDERECO_PROFISSIONAL FOREIGN KEY(IDENDERECO) REFERENCES ENDERECO(ID),
	IDESPECIALIDADE BIGINT,
	CONSTRAINT FK_ESPECIALIDADE_PROFISSIONAL FOREIGN KEY(IDESPECIALIDADE) REFERENCES ESPECIALIDADE(ID)
);