CREATE TABLE USUARIO(
	ID BIGSERIAL NOT NULL PRIMARY KEY,
	LOGIN VARCHAR(50),
	SENHA VARCHAR,
	IDPROFISSIONAL BIGINT,
	CONSTRAINT FK_PROFISSIONAL_USUARIO FOREIGN KEY(IDPROFISSIONAL) REFERENCES PROFISSIONAL(ID)
);