CREATE TABLE MEDICAMENTOUSO(
	ID BIGSERIAL NOT NULL PRIMARY KEY,
	INTERVALO INTEGER,
	QTDEVEZESAODIA INTEGER,
	DATAHORAINICIO TIMESTAMP,
	QTDEDIASUSO INTEGER,
	QTDEMEDICAMENTO INTEGER,
	IDRESIDENTE BIGINT,
	CONSTRAINT FK_RESIDENTE_MEDICAMENTO FOREIGN KEY(IDRESIDENTE) REFERENCES RESIDENTE(ID),
	IDMEDICAMENTO BIGINT,
	CONSTRAINT FK_MEDICAMENTOESTOQUE_MEDICAMENTOUSO FOREIGN KEY(IDMEDICAMENTO) REFERENCES MEDICAMENTOESTOQUE(ID)	
);