CREATE TABLE ENTRADASAIDA(
	ID BIGSERIAL NOT NULL PRIMARY KEY,
	DATAHORASAIDA TIMESTAMPTZ,
	DATAHORAENTRADA TIMESTAMPTZ,
	DESCRICAO VARCHAR(10),
	IDRESIDENTE BIGINT,
	CONSTRAINT FK_RESIDENTE_ENTRADASAIDA FOREIGN KEY(IDRESIDENTE) REFERENCES RESIDENTE(ID)
);