CREATE TABLE ENTRADASAIDA(
	ID BIGSERIAL NOT NULL PRIMARY KEY,
	DATAHORASAIDA TIMESTAMP,
	DATAHORAENTRADA TIMESTAMP,
	DESCRICAO VARCHAR(255),
	IDRESIDENTE BIGINT,
	CONSTRAINT FK_RESIDENTE_ENTRADASAIDA FOREIGN KEY(IDRESIDENTE) REFERENCES RESIDENTE(ID)
);