CREATE TABLE CONSULTA(
	ID BIGSERIAL NOT NULL PRIMARY KEY,
	DESCRICAO VARCHAR(255),
    DATAHORA TIMESTAMPTZ,
	LOCAL VARCHAR(100),
	PRESCRICAO VARCHAR(255),
	IDPROFISSIONAL BIGINT,
	CONSTRAINT FK_PROFISSIONAL_CONSULTA FOREIGN KEY(IDPROFISSIONAL) REFERENCES PROFISSIONAL(ID),
	IDRESIDENTE BIGINT,
	CONSTRAINT FK_RESIDENTE_CONSULTA FOREIGN KEY(IDRESIDENTE) REFERENCES RESIDENTE(ID),
	IDESPECIALIDADE BIGINT,
	CONSTRAINT FK_ESPECIALIDADE_CONSULTA FOREIGN KEY(IDESPECIALIDADE) REFERENCES ESPECIALIDADE(ID)
);