CREATE TABLE EXAME(
	ID BIGSERIAL NOT NULL PRIMARY KEY,
    DESCRICAO VARCHAR(255),
	DATAHORA TIMESTAMP,
	LOCAL VARCHAR(100),
	LAUDO VARCHAR(500),
	IDPROFISSIONAL BIGINT,
	CONSTRAINT FK_PROFISSIONAL_EXAME FOREIGN KEY(IDPROFISSIONAL) REFERENCES PROFISSIONAL(ID),
	IDRESIDENTE BIGINT,
	CONSTRAINT FK_RESIDENTE_EXAME FOREIGN KEY(IDRESIDENTE) REFERENCES RESIDENTE(ID),
	IDESPECIALIDADE BIGINT,
	CONSTRAINT FK_ESPECIALIDADE_EXAME FOREIGN KEY(IDESPECIALIDADE) REFERENCES ESPECIALIDADE(ID)
);