CREATE TABLE ATIVIDADEMEDICAMENTORESIDENTE(
	ID BIGSERIAL NOT NULL PRIMARY KEY,
	DESCRICAO VARCHAR(150),
	DATAHORA TIMESTAMP,
	SITUACAOATIVIDADE VARCHAR(12),
	IDTRATAMENTO BIGINT,
	CONSTRAINT FK_MEDICAMENTOUSO_ATIVIDADEMEDICAMENTO FOREIGN KEY(IDTRATAMENTO) REFERENCES MEDICAMENTOUSO(ID),
	IDPROFISSIONAL BIGINT,
	CONSTRAINT FK_PROFISSIONAL_ATIVIDADEMEDICAMENTO FOREIGN KEY(IDPROFISSIONAL) REFERENCES PROFISSIONAL(ID)
);