CREATE TABLE ATIVIDADEEXAMERESIDENTE(
	ID BIGSERIAL NOT NULL PRIMARY KEY,
	DESCRICAO VARCHAR(150),
	DATAHORA TIMESTAMP,
	SITUACAOATIVIDADE VARCHAR(12),
	IDEXAME BIGINT,
	CONSTRAINT FK_EXAME_ATIVIDADEEXAME FOREIGN KEY(IDEXAME) REFERENCES EXAME(ID),
    IDPROFISSIONAL BIGINT,
    CONSTRAINT FK_PROFISSIONAL_ATIVIDADEMEDICAMENTO FOREIGN KEY(IDPROFISSIONAL) REFERENCES PROFISSIONAL(ID)
);