CREATE TABLE ATIVIDADECONSULTARESIDENTE(
	ID BIGSERIAL NOT NULL PRIMARY KEY,
	DESCRICAO VARCHAR(150),
	DATAHORA TIMESTAMP,
	SITUACAOATIVIDADE VARCHAR(12),
	IDCONSULTA BIGINT,
	CONSTRAINT FK_CONSULTA_ATIVIDADECONSULTA FOREIGN KEY(IDCONSULTA) REFERENCES CONSULTA(ID),
    IDPROFISSIONAL BIGINT,
    CONSTRAINT FK_PROFISSIONAL_ATIVIDADEMEDICAMENTO FOREIGN KEY(IDPROFISSIONAL) REFERENCES PROFISSIONAL(ID)
);