CREATE TABLE ATIVIDADECONSULTARESIDENTE(
	ID BIGSERIAL NOT NULL PRIMARY KEY,
	DESCRICAO VARCHAR(150),
	DATAHORA TIMESTAMPTZ,
	SITUACAOATIVIDADE VARCHAR(12),
	IDCONSULTA BIGINT,
	CONSTRAINT FK_CONSULTA_ATIVIDADECONSULTA FOREIGN KEY(IDCONSULTA) REFERENCES CONSULTA(ID)
);