CREATE TABLE MOVIMENTACAOESTOQUE(
    ID BIGSERIAL NOT NULL PRIMARY KEY,
    QTDE INTEGER,
    TIPO VARCHAR(7),
    IDMEDICAMENTO BIGINT,
    CONSTRAINT FK_MEDICAMENTOESTOQUE_MOVIMENTACAOESTOQUE FOREIGN KEY(IDMEDICAMENTO) REFERENCES MEDICAMENTOESTOQUE(ID)
);