CREATE TABLE CONFIGURACAOSISTEMA(
    ID BIGSERIAL NOT NULL PRIMARY KEY,
    HABILITARENVIOEMAIL BOOLEAN DEFAULT FALSE,
    EMAILLOGIN VARCHAR(255),
    EMAILSENHA VARCHAR(255),
    HABILITARENVIOWHATS BOOLEAN DEFAULT FALSE,
    WHATSNUMEROID VARCHAR(255),
    WHATSTOKEN VARCHAR(500)
);

INSERT INTO CONFIGURACAOSISTEMA (HABILITARENVIOEMAIL,
                                 EMAILLOGIN,
                                 EMAILSENHA,
                                 HABILITARENVIOWHATS,
                                 WHATSNUMEROID,
                                 WHATSTOKEN)
VALUES (FALSE, NULL, NULL, FALSE, NULL, NULL);